# Reference: https://github.com/apache/infrastructure-asfyaml.
github:
  description: "NuttX Test Framework for Community."
  homepage: https://nuttx.apache.org/
  features:
    issues: true
  labels:
    - nuttx
    - rtos
    - embedded
    - pytest
  enabled_merge_buttons:
    squash: false
    merge: false
    rebase: true
